export const PREDEFINED_MATERIALS = [
  '95 Sq MM Black',
  '95 Sq MM Red',
  '70 Sq MM Black',
  '70 Sq MM Red',
  '50 Sq MM Black',
  '50 Sq MM Red',
  '35 Sq MM Black',
  '35 Sq MM Red',
  '16 Sq MM Green',
  '4 Sq MM 2Core Copper',
  '6 Sq MM 2 Core Copper',
  '16 Sq MM 2 Core Copper',
  '2.5 Sq MM 2 Core Copper',
  '0.5 Alarm Cable',
  '35 Sq MM 2 Core Copper',
  'GI Strip',
  'HDPE Pipe',
  '25 MM Flexible',
  '40 MM Flexible',
  '10 Pair Alarm Cable',
];
